@startuml GuardianEscolar
'Clase a observar'

interface AccionEstudiante {
    +subir(estudiante : Estudiante);
    +bajar(estudiante : Estudiante);
}

package IOvservable {
    interface IObservable {
        +agregarObservador(o : IObservador);
        +eliminarObservador(o : IObservador);
        +notificar();
    }

    class Bus {
        - placa : String
        - marca : String
        - capacidadPasajeros : int
        - vigenciaSOAT : MediumBlob
        - estadoSOAT : Boolean
        - estadoGPS : ENUM
        
        
        +actualizarVigenciaSOAT (estadoSOAT) : void
        +avisarVigenciaVencida (estadoSOAT) : void
        +actualizarEstadoGPS (estadoGPS) : void
        +avisarEstadoGPS (estadoGPS) : void

        +agregarObservador(o : IObservador);
        +eliminarObservador(o : IObservador);
        +notificar();

    }
}

package IObservador {
    interface IObservador {

    +recibirNotificacion(data : String);
    }
}

class Alerta { 
    - titulo : String
    - tipoAlerta : String
    - fechaHora : LocalDate
    - bus : Bus

    +crearAlerta (titulo, tipoAlerta, fechaHora, bus) : void
}

class Escuela {
    - nombre : String
    - direccion : String
    - ciudad : String
    - telefono : String
    - email : String
    - logo : TinyBlob
    - tema : ENUM
    
}
class Ruta {
    - codigo : String
    - sectorDestinado : String
    - horaInicio : LocalDate
    - horaFin : LocalDate
    - paradas : ArrayList<Parada>
    - pasajeros : ArrayList<Estudiente>
    
    +agregarPasajeros ( ) : void
    +eliminarPasajeros ( ) : void
    
    +agregarParadas ( ) : void
    +eliminarParadas ( ) : void
    +actualizarHoraInicio (horaInicio) : void
    +actualizarHoraFin (horaFin) : void

}
class Abordaje {
    -tipo
    -fechaHora : LocalDate
    - bus : Bus
    - usuario : usuario
    
    +agregarAbordaje (tipo, fechaHora, bus, usuario)
}
class Usuario {
    - nombreUsuario : String
    - contraseña : String
    - persona : arrayList<Persona>
}
class Persona {
    - nombre : String
    - apellido : String
    - direccion : String
    - telefono : int
    - email : String
    - tipoIdentificacion : Sting
    - identificacion : int
}
class Parada {
    - nombre : String
    - direccion : String
    - horaLlegada : LocalDate
}
class Curso {
    - nombre : String
    - grado : String
    -estudiantes : ArrayList<Estudiante>
}
class Conductor {
    - licencia : String
    - estadoLicencia : Boolean
    - vigenciaLicencia : MediumBlob
    
    +actualizarEstadoLicencia (estadoLicencia) : void
    +avisarVigenciaLicencia (vigenciaLicencia) : void
}

package Familias{
class Padre {
    +recibirNotificacion(data : String);
}
class Estudiante {

    +escanearQR(bus : Bus);
}
class Familia {
    - nombre : String
    - cantidadMiembros : int
    - Observaciones : String
    - estudiantes : ArrayList<Estudiante>
    - padres : ArrayList<Padre>
}

}
class Administrador {

}
interface PermisoUsuario {
    +verRuta ( ) : void
    +verAlertas ( ) : void
    +verAbordajes ( ) : void
    +verParadas ( ) : void
    +seleccionarRuta ( ) : void
    +actualizarInformacionPersonal ( ) : void
}
interface PermisoAdministrador {
    +registrarUsuario ( ) : void
    +eliminarUsuario ( ) : void
    +actualizarInformacionUsuario ( ) : void
    +asignarPermisos ( ) : void
    +verAlertas ( ) : void
    +crearRuta ( ) : void
    +eliminarRuta ( ) : void
    +actualizarRuta ( ) : void
    +crearParada ( ) : void
    +eliminarParada ( ) : void
    +verAbordajes ( ) : void
    +verParadas ( ) : void
    +verRutas ( ) : void
    +agregarBus ( ) : void
    +eliminarBus ( ) : void
    +actualizarInformacionPersonal ( ) : void
    +actualizarInoformacionBus ( ) : void
    +actualizarInformacionEscuela ( ) : void
}


'Relaciones'
Usuario <|--- PermisoUsuario
Usuario <|--- PermisoAdministrador

PermisoUsuario <|... Conductor
PermisoUsuario <|... Padre
PermisoUsuario <|... Estudiante
PermisoAdministrador <|... Administrador

' Implementaciones
Bus ..|> IObservable
Padre ..|> IObservador
Bus ..|> AccionEstudiante

'Asociaciones'
Alerta o--- Bus
Usuario o--- Alerta

Escuela o--- Usuario
Persona o--- Usuario
Curso o--- Estudiante

Bus o--- Ruta
Bus o--- Conductor
Bus o--- Estudiante


Ruta *--- Parada
Abordaje o--- Bus

Familia o--- Padre
Familia o--- Estudiante


@enduml
