@startuml GuardianEscolar
'Observer package'

package Observer {

    class Alert {
        - title : String
        - alertType : String
        - dateTime : LocalDate
        - bus : Bus

        +createAlert(title, alertType, dateTime, bus) : void
    }

    class Bus {
        - plate : String
        - brand : String
        - passengerCapacity : int
        - soatValidity : MediumBlob
        - soatStatus : Boolean
        - gpsStatus : ENUM
        - observers : List<IObserver>

        +addObserver(observer : IObserver)
        +removeObserver(observer : IObserver)
        +notifyObservers(message : String)

        +updateSoatValidity(soatStatus) : void
        +updateGpsStatus(gpsStatus) : void
    }

    interface IObserver {
        +receiveNotification(message : String)
    }

    note right of IObserver
        Recibe notificaciones del Bus cuando ocurre
        un evento, sin acoplarse directamente a él y se dirige al usuario
    end note
}

class School {
    - name : String
    - address : String
    - city : String
    - phone : String
    - email : String
    - logo : TinyBlob
    - theme : ENUM

}

package Comando-GestordeRutas {
    'Route management commands
    'Invoker
    class RouteManager {
        +executeCommand(command : Command) : void
    }

    'Command interface
    interface Command {
        +execute() : void
    }

    'Concrete commands
    class AddPassengerCommand {
        - route : Route
        - student : Student
        +execute() : void
    }

    class RemovePassengerCommand {
        - route : Route
        - student : Student
        +execute() : void
    }

    class AddStopCommand {
        - route : Route
        - stop : Stop
        +execute() : void
    }

    class RemoveStopCommand {
        - route : Route
        - stop : Stop
        +execute() : void
    }

    class UpdateStartTimeCommand {
        - route : Route
        - startTime : LocalDate
        +execute() : void
    }

    class UpdateEndTimeCommand {
        - route : Route
        - endTime : LocalDate
        +execute() : void
    }

    class Route {
        - code : String
        - targetSector : String
        - startTime : LocalDate
        - endTime : LocalDate
        - stops : ArrayList<Stop>
        - passengers : ArrayList<Student>

        +addPassenger(student) : void
        +removePassenger(student) : void
        +addStop(stop) : void
        +removeStop(stop) : void
    }
}

class Stop {
    - name : String
    - address : String
    - arrivalTime : LocalDate
}

class Boarding {
    - type
    - dateTime : LocalDate
    - bus : Bus
    - user : User

    +addBoarding(type, dateTime, bus, user)
}

class Course {
    - name : String
    - grade : String
    - students : ArrayList<Student>
}

Package Seguridad{
    'Security
    class Person {
        - firstName : String
        - lastName : String
        - address : String
        - phone : int
        - email : String
        - idType : String
        - idNumber : int
    }
}

package EstrategiasUsuario {
    class User {
        - username : String
        - password : String
        - person : Person
    }
    class Driver {
        - license : String
        - licenseStatus : Boolean
        - licenseValidity : MediumBlob

        +updateLicenseStatus(licenseStatus) : void
        +notifyLicenseExpiry(licenseValidity) : void
    }

    package Familias{
        class Parent {

        }
        class Student {
            +scanQR(bus : Bus)

        }
        class Family {
            - name : String
            - memberCount : int
            - observations : String
            - students : ArrayList<Student>
            - parents : ArrayList<Parent>
        }

    }
    class Administrator {

    }
    interface UserPermission {
        +viewRoute() : void
        +viewAlerts() : void
        +viewBoardings() : void
        +viewStops() : void
        +selectRoute() : void
        +updatePersonalInformation() : void
    }
    interface AdminPermission {
        +registerUser() : void
        +removeUser() : void
        +updateUserInformation() : void
        +assignPermissions() : void
        +viewAlerts() : void
        +createRoute() : void
        +removeRoute() : void
        +updateRoute() : void
        +createStop() : void
        +removeStop() : void
        +viewBoardings() : void
        +viewStops() : void
        +viewRoutes() : void
        +addBus() : void
        +removeBus() : void
        +updatePersonalInformation() : void
        +updateBusInformation() : void
        +updateSchoolInformation() : void
    }
}



'Relations'
User <|--- UserPermission
User <|--- AdminPermission

UserPermission <|... Driver
UserPermission <|... Parent
UserPermission <|... Student
AdminPermission <|... Administrator


'Associations'
Alert o--- Bus
User o--- Alert

School o--- User
Person o--- User
Course o--- Student

Bus o--- Route
Bus o--- Driver
Bus o--- Student


Route *--- Stop
Boarding o--- Bus

Family o--- Parent
Family o--- Student


'Command relations
Command <|.. AddPassengerCommand
Command <|.. RemovePassengerCommand
Command <|.. AddStopCommand
Command <|.. RemoveStopCommand
Command <|.. UpdateStartTimeCommand
Command <|.. UpdateEndTimeCommand

RouteManager --> Command
AddPassengerCommand --> Route
AddPassengerCommand --> Student
RemovePassengerCommand --> Route
RemovePassengerCommand --> Student
AddStopCommand --> Route
AddStopCommand --> Stop
RemoveStopCommand --> Route
RemoveStopCommand --> Stop
UpdateStartTimeCommand --> Route
UpdateEndTimeCommand --> Route

' Conexiones  observer
IObserver <|.. User
Bus --> IObserver

@enduml
