@startuml SchoolGuardian
skinparam Linetype ortho
!theme plain

package Families{
  entity Family {
    familyId: INTEGER <<PK>>
    --
    name: VARCHAR(255) <<NOT NULL>>
    observations: TEXT <<NOT NULL>>
  }

  entity FamilyMember {
    familyId: INTEGER <<PK>>
    profileId: INTEGER <<PK>>
  }
}

entity School {
  schoolId: INTEGER <<PK>> <<AUTO_INCREMENT>>
  cityId: INTEGER <<NOT NULL>>
  --
  logo: TINYBLOB
  name: VARCHAR(255) <<NOT NULL>>
  address: VARCHAR(255) <<NOT NULL>>
  phone: INTEGER <<NOT NULL>>
  email: VARCHAR(255) <<NOT NULL>>
  website: VARCHAR(255)
  theme: VARCHAR(255)
}

entity Boarding {
  profileId: INTEGER <<PK>>
  busId: INTEGER <<PK>>
  stopId: INTEGER <<NOT NULL>>
  --
  dateTime: TIMESTAMP <<NOT NULL>>
  action: BOOLEAN <<NOT NULL>>
}

package AlertControl {
  entity SavedAlert {
    profileId: INTEGER <<PK>>
    alertId: INTEGER <<PK>>
  }

  entity AlertTypes {
    alertTypeId: INTEGER <<PK>> <<AUTO_INCREMENT>>
    --
    name: VARCHAR(255) <<NOT NULL>>
    description: VARCHAR(255) <<NOT NULL>>
    urgencyLevel: INTEGER <<NOT NULL>>
  }

  entity Alert {
    alertId: INTEGER <<PK>>
    alertTypeId: INTEGER <<PK>>
    busId: INTEGER <<PK>>
    --
    dateTime: DATETIME <<NOT NULL>>
  }
}

entity Bus {
  busId: INTEGER <<PK>>
  driverId: INTEGER <<NOT NULL>>
  schoolId: INTEGER <<NOT NULL>>
  --
  brand: VARCHAR(255) <<NOT NULL>>
  model: VARCHAR(255) <<NOT NULL>>
  capacity: INTEGER <<NOT NULL>>
  soatValidity: MEDIUMBLOB <<NOT NULL>>
  gpsStatus: BOOLEAN <<NOT NULL>>
}

entity Stop {
  stopId: INTEGER <<PK>>
  cityId: INTEGER <<PK>>
  schoolId: INTEGER <<PK>>
  --
  address: VARCHAR(255) <<NOT NULL>>
  longitude: DECIMAL <<NOT NULL>>
  latitude: DECIMAL <<NOT NULL>>
}

entity Route {
  routeId: INTEGER <<PK>>
  schoolId: INTEGER <<PK>>
  --
  name: VARCHAR(255) <<NOT NULL>>
  targetSector: VARCHAR(255) <<NOT NULL>> <<UNIQUE>>
  startTime: TIME <<NOT NULL>>
  endTime: TIME <<NOT NULL>>
}


entity Cities {
  cityId: INTEGER <<PK>> <<AUTO_INCREMENT>>
  --
  name: VARCHAR(255) <<NOT NULL>>
  country: VARCHAR(255) <<NOT NULL>>
}

entity RouteStudentAssignments {
  profileId: INTEGER <<PK>>
  routeId: INTEGER <<PK>>
}

entity RouteStop {
  routeId: INTEGER <<PK>>
  stopId: INTEGER <<PK>>
}

entity RouteBusAssignments {
  busId: INTEGER <<PK>>
  routeId: INTEGER <<PK>>
}

entity SchoolCampuse {
  campusId: INTEGER <<PK>> <<AUTO_INCREMENT>>
  schoolId: INTEGER <<NOT NULL>>
  --
  name: VARCHAR(255) <<NOT NULL>>
  address: VARCHAR(255) <<NOT NULL>>
}

entity Course {
  courseId: INTEGER <<PK>> <<AUTO_INCREMENT>>
  campusId: INTEGER <<NOT NULL>>
  --
  name: VARCHAR(255) <<NOT NULL>>
}

entity CourseGroup {
  profileId: INTEGER <<PK>>
  courseId: INTEGER <<PK>>
}

entity DriverLicense {
  licenseId: INTEGER <<PK>>
  profileId: INTEGER <<NOT NULL>>
  --
  licenseNumber: VARCHAR(255)
  drivingLicense: MEDIUMBLOB <<NOT NULL>>
  licenseExpirationDate: DATE <<NOT NULL>>
}

entity ProfileRol {
  profileId: INTEGER <<PK>>
  roleId: INTEGER <<PK>>
}

entity ExceptionalDriverUsage {
  usageId: INTEGER <<PK>> <<AUTO_INCREMENT>>
  busId: INTEGER <<NOT NULL>>
  profileId: INTEGER <<NOT NULL>>
  --
  startDateTime: DATETIME <<NOT NULL>>
  endDateTime: DATETIME <<NOT NULL>>
  reason: VARCHAR(255) <<NOT NULL>>
}

entity ExceptionalRouteUsage {
  usageId: INTEGER <<PK>> <<AUTO_INCREMENT>>
  profileId: INTEGER <<NOT NULL>>
  routeId: INTEGER <<NOT NULL>>
  --
  dateTime: DATETIME <<NOT NULL>>
  reason: VARCHAR(255)
}

package SecureModule {

  entity Profile {
    profileId: INTEGER <<PK>> <<AUTO_INCREMENT>>
    --
    name: VARCHAR(255) <<NOT NULL>>
    lastName: VARCHAR(255) <<NOT NULL>>
    identificationType: VARCHAR(255) <<NOT NULL>>
    identificationNumber: INTEGER <<NOT NULL>>
    email: VARCHAR(255) <<NOT NULL>>
    phone: INTEGER <<NOT NULL>>
    residenceAddress: VARCHAR(255) <<NOT NULL>>
    password: VARCHAR(255) <<NOT NULL>>
  }

  entity Role {
    roleId: INTEGER <<PK>> <<AUTO_INCREMENT>>
    --
    name: VARCHAR(255) <<NOT NULL>>
    description: VARCHAR(255) <<NOT NULL>>
    permissions: VARCHAR(255) <<NOT NULL>>
  }
  entity Action {
    actionId INTEGER <<PK>> <<AUTO_INCREMENT>>
    --
    name VARCHAR(255)
    description TEXT
  }

  entity View {
    viewId INTEGER <<PK>> <<AUTO_INCREMENT>>
    --
    name VARCHAR(255)
    description TEXT
  }

  entity Module {
    modueId INTEGER <<PK>> <<AUTO_INCREMENT>>
    --
    name VARCHAR(255)
    description TEXT
  }

  entity RoleModule {
    roleModuleId <<PK>> <<AUTO_INCREMENT>>
    roleId <<FK>>
    moduleId <<FK>>
  }

  entity ViewModule {
    viewModuleId <<PK>> <<AUTO_INCREMENT>>
    viewId <<FK>>
    moduleId <<FK>>
  }

  entity ViewAction {
    viewActionId <<PK>> <<AUTO_INCREMENT>>
    viewId <<FK>>
    actionId <<FK>>
  }
}

' Relaciones

SavedAlert }o--|| Profile : "profileId -> profileId"
SavedAlert }o--|| Alert : "alertId -> alertId"

Alert }o--|| AlertTypes : "alertTypeId -> alertTypeId"
Alert }o--|| Bus : "busId -> busId"

SchoolCampuse }o--|| School : "schoolId -> schoolId"

Profile ||--o{ FamilyMember : "profileId -> profileId"
Family ||--o{ FamilyMember : "familyId -> familyId"

Boarding }o--|| Profile : "profileId -> profileId"
Boarding }o--|| Bus : "busId -> busId"
Boarding }o--|| Stop : "stopId -> stopId"

Stop }o--|| Cities : "cityId -> cityId"
School }o--|| Cities : "cityId -> cityId"

RouteStudentAssignments }o--|| Route : "routeId -> routeId"
RouteStudentAssignments ||--|| Profile : "profileId -> profileId"

RouteStop }o--|| Route : "routeId -> routeId"
RouteStop }o--|| Stop : "stopId -> stopId"

RouteBusAssignments }o--|| Bus : "busId -> busId"
RouteBusAssignments }o--|| Route : "routeId -> routeId"

Bus }o--|| School : "schoolId -> schoolId"
Bus }o--|| Profile : "driverId -> profileId"

Stop }o--|| School : "schoolId -> schoolId"

Route }o--|| School : "schoolId -> schoolId"

Course }o--|| SchoolCampuse : "campusId -> campusId"

CourseGroup }o--|| Profile : "profileId -> profileId"
CourseGroup }o--|| Course : "courseId -> courseId"

DriverLicense ||--|| Profile : "profileId -> profileId"

ProfileRol }o--|| Profile : "profileId -> profileId"
ProfileRol }o--|| Role : "roleId -> roleId"

ExceptionalDriverUsage }o--|| Bus : "busId -> busId"
ExceptionalDriverUsage }o--|| Profile : "profileId -> profileId"

ExceptionalRouteUsage }o--|| Profile : "profileId -> profileId"
ExceptionalRouteUsage }o--|| Route : "routeId -> routeId"

Module ||--o{ RoleModule
Role ||--o{ RoleModule

View ||-o{ ViewAction
Action ||--o{ ViewAction

View ||--o{ ViewModule
Module ||--o{ ViewModule
@enduml